(ns kaisya.bpmn
  "Generate `resources/kaisya/processes.edn` from `bpmn/*.bpmn`.

  The BPMN files are the inherited record of how this company's work is
  supposed to flow (see `migration.edn` for where they came from). The portal
  needs to *name* those processes; it does not need to execute them.

  This reads them rather than transcribing them by hand, and that is the whole
  point of the namespace existing: a hand-copied list is a second source of
  truth that drifts silently the first time somebody edits the diagram, and
  the drift is invisible because both look plausible. `processes-are-current`
  in the test suite re-runs this extraction and fails if the checked-in EDN
  disagrees with the files.

  Deliberately regex, not an XML parser: the extraction is `id` + `name` +
  element type off elements that are one-per-line in these files, and pulling
  in a parser to read four attributes would be a dependency this repository
  otherwise does not need. If the BPMN ever needs real structure — flows,
  gateways, conditions — replace this with a parser rather than growing the
  regex."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.string :as str]))

(def ^:private step-elements
  "Element names that represent a step somebody performs or a decision the
  process makes. `sequenceFlow` and the `bpmndi:*` layout elements are
  excluded — they are how the diagram draws, not what the company does."
  {"startEvent" :start
   "endEvent" :end
   "userTask" :user-task
   "serviceTask" :service-task
   "businessRuleTask" :decision
   "scriptTask" :script-task
   "sendTask" :send-task
   "receiveTask" :receive-task
   "manualTask" :manual-task
   "exclusiveGateway" :gateway
   "parallelGateway" :parallel-gateway
   "inclusiveGateway" :inclusive-gateway
   "callActivity" :call-activity})

(defn- attr [s k]
  (second (re-find (re-pattern (str "\\b" k "=\"([^\"]*)\"")) s)))

(defn- elements
  "Every opening tag in `xml` whose local name is in `step-elements`, in
  document order."
  [xml]
  (for [[_ tag rest-of-tag] (re-seq #"<(?:\w+:)?(\w+)([^>]*)>" xml)
        :let [kind (get step-elements tag)]
        :when kind
        :let [id (attr rest-of-tag "id")]
        :when id]
    {:step/id id :step/kind kind :step/name (or (attr rest-of-tag "name") id)}))

(defn- process-of [xml file]
  (let [head (re-find #"<(?:\w+:)?process\b[^>]*>" xml)]
    {:process/id (or (attr head "id") (str/replace (.getName (io/file file)) #"\.bpmn$" ""))
     :process/name (or (attr head "name") "(名称なし)")
     :process/source (str "bpmn/" (.getName (io/file file)))
     :process/steps (vec (elements xml))}))

(defn extract
  "Every process in `bpmn/`, sorted by id so the generated file is stable."
  ([] (extract "bpmn"))
  ([dir]
   (->> (file-seq (io/file dir))
        (filter #(str/ends-with? (.getName ^java.io.File %) ".bpmn"))
        (sort-by #(.getName ^java.io.File %))
        (mapv #(process-of (slurp %) %)))))

(def output-path "resources/kaisya/processes.edn")

(defn -main [& _]
  (let [ps (extract)]
    (io/make-parents output-path)
    (spit output-path
          (str ";; GENERATED by `clojure -M:emit-processes` from bpmn/*.bpmn.\n"
               ";; Do not hand-edit — `kaisya.bpmn-test/processes-are-current`\n"
               ";; re-runs the extraction and fails on any difference.\n"
               (with-out-str (pprint/pprint ps))))
    (println (str "wrote " output-path " — " (count ps) " processes, "
                  (reduce + 0 (map (comp count :process/steps) ps)) " steps"))))

(defn checked-in
  "The generated file as data, for the currency test and for the portal."
  []
  (some-> (io/resource "kaisya/processes.edn") slurp edn/read-string))
